"""Build the documentation site, in the usual LinkML style.

    python -m <slug>.docs generate   # write the generated pages into docs/
    python -m <slug>.docs build      # generate, then build the site into site/
    python -m <slug>.docs serve      # generate, then serve the site locally

Generated, and not committed:
  docs/elements/     one page per class, slot, enum and type (LinkML gen-doc),
                     with class diagrams and the example record inline
  docs/structure.md  what a record can contain, as one diagram
  docs/corpus.md     counts from the records
  docs/schema/       the schema with imports merged, and as JSON Schema
  docs/records/      the record browser, rendered fresh, when the Mech has one

Colors and light or dark mode come from conf/site.yaml: `build` and `serve`
write .mkdocs.site.yml, which inherits mkdocs.yml and replaces its palette.
`build` runs MkDocs in strict mode, so a broken link fails. Every link to the
record browser is relative, so the site works wherever it is hosted.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

import yaml

from . import site
from .paths import BUILD_DIR, MECH_NAME, PACKAGE_DIR, PAGES_DIR, RECORD_CLASS, REPO_ROOT, SCHEMA_PATH, SLUG
from .report import compute

DOCS = REPO_ROOT / "docs"
SITE = REPO_ROOT / "site"
EXAMPLE = REPO_ROOT / "tests" / "data" / "example_record.yaml"
SITE_CONFIG = REPO_ROOT / ".mkdocs.site.yml"


def write_site_config() -> Path:
    """mkdocs.yml, with the palette from conf/site.yaml."""
    settings = site.load()
    errors = site.problems(settings)
    if errors:
        raise SystemExit("conf/site.yaml: " + "; ".join(errors))
    colors = {"primary": settings["palette"], "accent": settings["accent"]}
    light = {"scheme": "default", **colors}
    dark = {"scheme": "slate", **colors}
    if settings["theme"] == "light":
        palette = [light]
    elif settings["theme"] == "dark":
        palette = [dark]
    else:
        palette = [
            {"media": "(prefers-color-scheme: light)", **light,
             "toggle": {"icon": "material/brightness-4", "name": "Dark mode"}},
            {"media": "(prefers-color-scheme: dark)", **dark,
             "toggle": {"icon": "material/brightness-7", "name": "Light mode"}},
        ]
    config = {"INHERIT": "mkdocs.yml", "theme": {"name": "material", "palette": palette}}
    SITE_CONFIG.write_text("# Generated by docs.py from conf/site.yaml. Do not edit.\n"
                           + yaml.safe_dump(config, sort_keys=False))
    return SITE_CONFIG


def generate() -> None:
    from linkml.generators.docgen import DocGenerator
    from linkml.generators.erdiagramgen import ERDiagramGenerator
    from linkml.generators.jsonschemagen import JsonSchemaGenerator
    from linkml.generators.yamlgen import YAMLGenerator

    # Class pages show examples named <Class>-<name>.yaml.
    examples = BUILD_DIR / "doc-examples"
    shutil.rmtree(examples, ignore_errors=True)
    examples.mkdir(parents=True)
    if EXAMPLE.exists():
        shutil.copy(EXAMPLE, examples / f"{RECORD_CLASS}-example.yaml")

    elements = DOCS / "elements"
    shutil.rmtree(elements, ignore_errors=True)
    # Classes, slots, enums and types each get a folder. In one folder, the Term
    # class and the term slot are Term.md and term.md, which are the same file
    # on a filesystem that ignores case (macOS, Windows): one overwrites the
    # other and the build fails on the links to the lost page.
    DocGenerator(
        str(SCHEMA_PATH), example_directory=str(examples), subfolder_type_separation=True
    ).serialize(directory=str(elements))

    diagram = ERDiagramGenerator(str(SCHEMA_PATH), structural=True).serialize()
    (DOCS / "structure.md").write_text(
        f"# Record structure\n\n"
        f"Everything a `{RECORD_CLASS}` record can contain, from the record down. "
        f"Each class links to its page under [Schema](elements/index.md).\n\n{diagram}\n"
    )

    schema_out = DOCS / "schema"
    shutil.rmtree(schema_out, ignore_errors=True)
    schema_out.mkdir(parents=True)
    (schema_out / f"{SLUG}.yaml").write_text(YAMLGenerator(str(SCHEMA_PATH), mergeimports=True).serialize())
    (schema_out / f"{SLUG}.schema.json").write_text(
        JsonSchemaGenerator(str(SCHEMA_PATH), not_closed=False, top_class=RECORD_CLASS).serialize()
    )

    records = DOCS / "records"
    shutil.rmtree(records, ignore_errors=True)
    if (PACKAGE_DIR / "render.py").exists():
        # Render the browser here rather than copy pages/: it then exists
        # even before the first record, and always matches the records.
        from .render import build as render_browser

        for path, text in render_browser().items():
            out = records / path.relative_to(PAGES_DIR)
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(text)

    stats = compute()
    rows = "\n".join(
        f"| {k.replace('_', ' ')} | {v} |" for k, v in stats.items() if k not in ("mech", "by_status")
    )
    status = "\n".join(f"| {k} | {v} |" for k, v in stats["by_status"].items()) or "| none | 0 |"
    (DOCS / "corpus.md").write_text(
        f"# Corpus\n\nCounted from the records when this site was built. "
        f"`just report` gives the same numbers.\n\n"
        f"| Measure | Count |\n|---|---|\n{rows}\n\n"
        f"## Records by status\n\n| Status | Records |\n|---|---|\n{status}\n"
    )
    print(f"Generated docs/elements/, docs/schema/, docs/structure.md and docs/corpus.md for {MECH_NAME}.")


def build() -> int:
    generate()
    shutil.rmtree(SITE, ignore_errors=True)
    config = write_site_config()
    cmd = [sys.executable, "-m", "mkdocs", "build", "--strict", "-f", str(config), "-d", str(SITE)]
    result = subprocess.run(cmd, cwd=REPO_ROOT)
    if result.returncode != 0:
        return result.returncode
    print(f"Built the site in {SITE.relative_to(REPO_ROOT)}/.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("command", choices=["generate", "build", "serve"])
    args = parser.parse_args(argv)
    if args.command == "generate":
        generate()
        return 0
    if args.command == "serve":
        generate()
        return subprocess.run([sys.executable, "-m", "mkdocs", "serve", "-f", str(write_site_config())],
                              cwd=REPO_ROOT).returncode
    return build()


if __name__ == "__main__":
    sys.exit(main())
